# Coursera Applied Data Science Capstone - Alvaro Suarez Mateos

* This is the notebook that I will use to complete the Applied Data Science Capstone module and which will live in GitHub.

In [1]:
import pandas as pd
import numpy as np
print('Hello Capstone Project Course!')

Hello Capstone Project Course!

For this week, you will required to submit the following:

* A description of the problem and a discussion of the background. (15 marks)
* A description of the data and how it will be used to solve the problem. (15 marks)

# Introduction/Business Problem

* The highest price we pay for car crashes is in the loss of human lives, however society also bears the brunt of the many costs associated with motor vehicle accidents. According to the National Highway Traffic Safety Administration (NHTSA), U.S. motor vehicle crashes in 2010 cost almost $1 trillion in loss of productivity and loss of life.

* Data scientists can contribute to the debate of how to reduce the severity of car accidents by contributing their opinions based on extensive data analysis of traffic incident datasets. Via exploratory analysis, data scientists have the potential to uncover hidden patterns. One human life that is lost in a traffic incident is one too many, hence the importance of making sure the data community contributes to the debate.

* Machine Learning is,at its most basic, the practice of using algorithms to parse data, learn from it, and then make a determination or prediction about something in the world. Given the existence of multiple datasets that incorporate data about traffic incidents, we can leverage this to apply machine learning and other data analysis techniques to the problem of traffic incidents.

* The City of Seattle has a publicly available dataset on traffic incidents in the city, which we will use for our analysis. Our end-goal is to be able to understand the factors that increase the likelihood of a traffic incident in Seattle, and whether we can predict the severity of an incident based ona series of attributes pertaining to the incident.

* **The target audience** for this project is the local government of the City of Seattle, in addition to local organisations that are involved in the neighbourhoods of Seattle.

# Data

Our dataset can be accessed via the following link https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv, and is made up of 38 columns and 194673 rows.

Therefore, we have 38 attributes to play with in our analysis, and 194673 instances of traffic incidents.

At a quick glance, attributes such as the following might prove useful throughout our analysis:

* **SEVERITYCODE:** A code that corresponds to the severity of the collision:
                    - 3—fatality
                    - 2b—serious injury
                    - 2—injury
                    - 1—prop damage
                    - 0—unknown
                    
* **ADDRTYPE:** Collision address type:
                    - Alley
                    - Block
                    - Intersection

* **LOCATION:** Description of the general location of the collision (street name and number)

* **SEVERITYCODE:** A code that corresponds to the severity of the collision:
                    - 3—fatality
                    - 2b—serious injury
                    - 2—injury
                    - 1—prop damage
                    - 0—unknown
                    
* **PERSONCOUNT:** The total number of people involved in the collision

* **INCDATE:** The date of the incident.


The label for the data set is severity, which describes the fatality of an accident.

* From some initial exploratory analysis, we have seen that some of the attributes in our dataset have missing values. In fact, 17 out of the 38 attributes have at least one NaN value. 7 attributes have more than 10% of the rows with NaN values and it is likely we will drop some of these.

* We can see how our dataset looks:

In [4]:
df = pd.read_csv('/Users/amateos/Downloads/Data-Collisions.csv')
df.head()

/Users/amateos/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,1,1307,1307,3502005,Matched,Intersection,37475.0,...,Wet,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,2,52200,52200,2607959,Matched,Block,NaN,...,Wet,Dark - Street Lights On,NaN,6354039.0,NaN,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,3,26700,26700,1482393,Matched,Block,NaN,...,Dry,Daylight,NaN,4323031.0,NaN,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,4,1144,1144,3503937,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,5,17700,17700,1807429,Matched,Intersection,34387.0,...,Wet,Daylight,NaN,4028032.0,NaN,10,Entering at angle,0,0,N